/**
 * Final exam — a bespoke 100-question test covering every lesson in the course.
 * Gated until all lessons are completed (see src/app/(app)/exam/page.tsx). Uses the same
 * mastery-loop Quiz as lessons: 100% to pass, and every missed question is re-asked until
 * answered correctly (owner decision). Saved under the reserved slug "final-exam".
 *
 * Questions are grouped by source lesson for traceability. Bilingual EN + Taglish.
 */
import type { QuizQuestion } from "./schema";

const TF = () => [
  { id: "t", text: { en: "True", tl: "Tama" } },
  { id: "f", text: { en: "False", tl: "Mali" } },
];

export const finalExam: QuizQuestion[] = [
  // ── How to Read Charts (primer) ──
  {
    id: "fx1",
    type: "mcq",
    prompt: { en: "A candlestick's body shows which two prices?", tl: "Anong dalawang presyo ang ipinapakita ng body ng candlestick?" },
    options: [
      { id: "a", text: { en: "The open and the close", tl: "Ang open at close" } },
      { id: "b", text: { en: "The high and the low", tl: "Ang high at low" } },
      { id: "c", text: { en: "The spread and the volume", tl: "Ang spread at volume" } },
      { id: "d", text: { en: "Two random prices", tl: "Dalawang random na presyo" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The body spans the open and close; the wicks show the high and low.", tl: "Ang body ay ang open at close; ang wicks ang high at low." },
  },
  {
    id: "fx2",
    type: "mcq",
    prompt: { en: "The thin lines above and below a candle's body are the…", tl: "Ang manipis na linya sa itaas at ibaba ng body ay ang…" },
    options: [
      { id: "a", text: { en: "Wicks (the high and low)", tl: "Wicks (ang high at low)" } },
      { id: "b", text: { en: "Open and close", tl: "Open at close" } },
      { id: "c", text: { en: "Moving averages", tl: "Moving averages" } },
      { id: "d", text: { en: "Support lines", tl: "Support lines" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The wicks reach to the candle's high and low.", tl: "Ang wicks ay umaabot sa high at low ng candle." },
  },
  {
    id: "fx3",
    type: "truefalse",
    prompt: { en: "An up (bullish) candle closes above its open.", tl: "Ang up (bullish) na candle ay nag-cclose sa itaas ng open nito." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Up candle: close above open. Down candle: close below open.", tl: "Oo. Up candle: close sa itaas ng open. Down candle: close sa ibaba." },
  },
  {
    id: "fx4",
    type: "mcq",
    prompt: { en: "On a down (bearish) candle, the top of the body is the…", tl: "Sa down (bearish) na candle, ang taas ng body ay ang…" },
    options: [
      { id: "a", text: { en: "Open", tl: "Open" } },
      { id: "b", text: { en: "Close", tl: "Close" } },
      { id: "c", text: { en: "High", tl: "High" } },
      { id: "d", text: { en: "Low", tl: "Low" } },
    ],
    correctOptionId: "a",
    explanation: { en: "On a down candle the open is on top and the close is at the bottom.", tl: "Sa down candle, nasa taas ang open at nasa baba ang close." },
  },

  // ── Market Structure Part 1 ──
  {
    id: "fx5",
    type: "mcq",
    prompt: { en: "A Higher Low (HL) is a low that sits…", tl: "Ang Higher Low (HL) ay low na…" },
    options: [
      { id: "a", text: { en: "Above the previous low", tl: "Mas mataas sa nakaraang low" } },
      { id: "b", text: { en: "Below the previous low", tl: "Mas mababa sa nakaraang low" } },
      { id: "c", text: { en: "At the open", tl: "Sa open" } },
      { id: "d", text: { en: "Above the previous high", tl: "Sa itaas ng nakaraang high" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An HL is higher than the previous low, a bullish sign.", tl: "Ang HL ay mas mataas sa nakaraang low, bullish na senyales." },
  },
  {
    id: "fx6",
    type: "mcq",
    prompt: { en: "A bullish market is made of…", tl: "Ang bullish market ay binubuo ng…" },
    options: [
      { id: "a", text: { en: "Higher highs and higher lows", tl: "Higher highs at higher lows" } },
      { id: "b", text: { en: "Lower lows and lower highs", tl: "Lower lows at lower highs" } },
      { id: "c", text: { en: "Equal highs only", tl: "Equal highs lang" } },
      { id: "d", text: { en: "No structure", tl: "Walang structure" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Higher highs + higher lows = bullish.", tl: "Higher highs + higher lows = bullish." },
  },
  {
    id: "fx7",
    type: "mcq",
    prompt: { en: "A bearish market is made of…", tl: "Ang bearish market ay binubuo ng…" },
    options: [
      { id: "a", text: { en: "Lower lows and lower highs", tl: "Lower lows at lower highs" } },
      { id: "b", text: { en: "Higher highs and higher lows", tl: "Higher highs at higher lows" } },
      { id: "c", text: { en: "Equal lows only", tl: "Equal lows lang" } },
      { id: "d", text: { en: "Gaps only", tl: "Gaps lang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Lower lows + lower highs = bearish.", tl: "Lower lows + lower highs = bearish." },
  },
  {
    id: "fx8",
    type: "truefalse",
    prompt: { en: "We focus on trending markets because they are higher-probability.", tl: "Nakapokus tayo sa trending markets dahil mas mataas ang probability." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Trends give clearer, higher-probability moves than ranges.", tl: "Oo. Mas malinaw at high-probability ang trends kaysa ranges." },
  },
  {
    id: "fx9",
    type: "mcq",
    prompt: { en: "A Lower High (LH) is a high that sits…", tl: "Ang Lower High (LH) ay high na…" },
    options: [
      { id: "a", text: { en: "Below the previous high", tl: "Mas mababa sa nakaraang high" } },
      { id: "b", text: { en: "Above the previous high", tl: "Mas mataas sa nakaraang high" } },
      { id: "c", text: { en: "At the close", tl: "Sa close" } },
      { id: "d", text: { en: "Below the previous low", tl: "Sa ilalim ng nakaraang low" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An LH is lower than the previous high, a bearish sign.", tl: "Ang LH ay mas mababa sa nakaraang high, bearish na senyales." },
  },

  // ── Market Structure Part 2 ──
  {
    id: "fx10",
    type: "mcq",
    prompt: { en: "Before judging if structure continues or breaks, you must first…", tl: "Bago husgahan kung tuloy o break ang structure, dapat mo munang…" },
    options: [
      { id: "a", text: { en: "Correctly identify the swing highs and lows", tl: "Tama na ma-identify ang swing highs at lows" } },
      { id: "b", text: { en: "Add indicators", tl: "Magdagdag ng indicators" } },
      { id: "c", text: { en: "Check the news", tl: "Tingnan ang balita" } },
      { id: "d", text: { en: "Increase leverage", tl: "Taasan ang leverage" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Everything depends on reading swing points correctly first.", tl: "Lahat ay nakadepende sa tamang pagbasa ng swing points muna." },
  },
  {
    id: "fx11",
    type: "truefalse",
    prompt: { en: "Breaking the last higher low in an uptrend can warn of a reversal.", tl: "Ang pag-break sa huling higher low sa uptrend ay pwedeng babala ng reversal." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. A broken higher low warns the bullish structure may be shifting.", tl: "Oo. Babala ang na-break na higher low na pwedeng mag-shift ang structure." },
  },
  {
    id: "fx12",
    type: "mcq",
    prompt: { en: "The beginner reward-to-risk target taught is…", tl: "Ang beginner reward-to-risk target na itinuturo ay…" },
    options: [
      { id: "a", text: { en: "1:2", tl: "1:2" } },
      { id: "b", text: { en: "1:1", tl: "1:1" } },
      { id: "c", text: { en: "1:0.5", tl: "1:0.5" } },
      { id: "d", text: { en: "10:1", tl: "10:1" } },
    ],
    correctOptionId: "a",
    explanation: { en: "1:2 protects win-rate and psychology as a beginner.", tl: "Pinoprotektahan ng 1:2 ang win-rate at psychology bilang beginner." },
  },
  {
    id: "fx13",
    type: "mcq",
    prompt: { en: "Why is a ranging market a trap?", tl: "Bakit trap ang ranging market?" },
    options: [
      { id: "a", text: { en: "No clean structure, so either side's liquidity can be taken", tl: "Walang malinis na structure, kaya pwedeng makuha ang liquidity ng magkabila" } },
      { id: "b", text: { en: "It never moves", tl: "Hindi gumagalaw" } },
      { id: "c", text: { en: "Brokers ban it", tl: "Bina-ban ng broker" } },
      { id: "d", text: { en: "It is always bullish", tl: "Lagi itong bullish" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Ranges lack clean structure; both highs and lows get taken: low probability.", tl: "Walang malinis na structure ang range; nakukuha ang highs at lows: low probability." },
  },

  // ── MSB & MSS ──
  {
    id: "fx14",
    type: "mcq",
    prompt: { en: "A Market Structure Break (MSB) happens…", tl: "Ang Market Structure Break (MSB) ay nangyayari…" },
    options: [
      { id: "a", text: { en: "Along the trend (continuation)", tl: "Kasabay ng trend (continuation)" } },
      { id: "b", text: { en: "Against the trend (reversal)", tl: "Kontra sa trend (reversal)" } },
      { id: "c", text: { en: "Only at the open", tl: "Sa open lang" } },
      { id: "d", text: { en: "Only on weekends", tl: "Tuwing weekend lang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "MSB is a continuation break in the trend direction.", tl: "Ang MSB ay continuation break sa direksyon ng trend." },
  },
  {
    id: "fx15",
    type: "mcq",
    prompt: { en: "A Market Structure Shift (MSS) signals…", tl: "Ang Market Structure Shift (MSS) ay senyales ng…" },
    options: [
      { id: "a", text: { en: "A reversal", tl: "Reversal" } },
      { id: "b", text: { en: "Continuation", tl: "Continuation" } },
      { id: "c", text: { en: "Lower volume", tl: "Mababang volume" } },
      { id: "d", text: { en: "Nothing", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "MSS breaks structure against the trend: a reversal.", tl: "Nira-break ng MSS ang structure kontra sa trend: reversal." },
  },
  {
    id: "fx16",
    type: "truefalse",
    prompt: { en: "A level counts as broken only once it is actually taken out.", tl: "Bilang lang na break ang level kapag na-take out na talaga." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Approaching a level is not a break; it must be taken out.", tl: "Oo. Hindi break ang papalapit pa lang; kailangang ma-take out." },
  },
  {
    id: "fx17",
    type: "mcq",
    prompt: { en: "An MSS reversal typically happens after price hits a…", tl: "Karaniwang nangyayari ang MSS reversal pagkatapos tumama sa…" },
    options: [
      { id: "a", text: { en: "Higher-timeframe POI (support/resistance)", tl: "Higher-timeframe POI (support/resistance)" } },
      { id: "b", text: { en: "Round number", tl: "Round number" } },
      { id: "c", text: { en: "Moving average", tl: "Moving average" } },
      { id: "d", text: { en: "Random candle", tl: "Random na candle" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The shift usually follows a reaction at a higher-timeframe POI.", tl: "Karaniwang sumusunod ang shift sa reaksyon sa higher-timeframe POI." },
  },
  {
    id: "fx18",
    type: "mcq",
    prompt: { en: "Points of interest are also called…", tl: "Ang points of interest ay tinatawag ding…" },
    options: [
      { id: "a", text: { en: "Premium & discount arrays (PDRAs)", tl: "Premium & discount arrays (PDRAs)" } },
      { id: "b", text: { en: "Moving averages", tl: "Moving averages" } },
      { id: "c", text: { en: "Trendlines", tl: "Trendlines" } },
      { id: "d", text: { en: "Pivots only", tl: "Pivots lang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "POIs = PDRAs: OBs, FVGs, breakers, and more.", tl: "POIs = PDRAs: OBs, FVGs, breakers, at iba pa." },
  },

  // ── Liquidity ──
  {
    id: "fx19",
    type: "mcq",
    prompt: { en: "Buy-side liquidity (BSL) rests…", tl: "Ang buy-side liquidity (BSL) ay nasa…" },
    options: [
      { id: "a", text: { en: "Above highs / resistance", tl: "Itaas ng highs / resistance" } },
      { id: "b", text: { en: "Below lows / support", tl: "Ilalim ng lows / support" } },
      { id: "c", text: { en: "At the open", tl: "Sa open" } },
      { id: "d", text: { en: "Nowhere", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "BSL sits above highs, where shorts' stops and breakout buys cluster.", tl: "Nasa itaas ng highs ang BSL, kung saan ang stops ng shorts at breakout buys." },
  },
  {
    id: "fx20",
    type: "mcq",
    prompt: { en: "Sell-side liquidity (SSL) rests…", tl: "Ang sell-side liquidity (SSL) ay nasa…" },
    options: [
      { id: "a", text: { en: "Below lows / support", tl: "Ilalim ng lows / support" } },
      { id: "b", text: { en: "Above highs / resistance", tl: "Itaas ng highs / resistance" } },
      { id: "c", text: { en: "At the close", tl: "Sa close" } },
      { id: "d", text: { en: "Only on indices", tl: "Sa indices lang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "SSL sits below lows, where longs' stops cluster.", tl: "Nasa ilalim ng lows ang SSL, kung saan ang stops ng longs." },
  },
  {
    id: "fx21",
    type: "truefalse",
    prompt: { en: "A breakout above resistance always continues higher.", tl: "Ang breakout above resistance ay laging tuloy pataas." },
    options: TF(),
    correctOptionId: "f",
    explanation: { en: "False. Often it just sweeps liquidity, then reverses: a trap.", tl: "Mali. Madalas nag-sweep lang ng liquidity, tapos reversal: trap." },
  },
  {
    id: "fx22",
    type: "mcq",
    prompt: { en: "Market makers mostly target…", tl: "Kadalasang tina-target ng market makers ang…" },
    options: [
      { id: "a", text: { en: "The stop losses / liquidity of retail traders", tl: "Stop losses / liquidity ng retail traders" } },
      { id: "b", text: { en: "Indicator signals", tl: "Mga signal ng indicator" } },
      { id: "c", text: { en: "News headlines", tl: "Mga news headline" } },
      { id: "d", text: { en: "Round numbers", tl: "Round numbers" } },
    ],
    correctOptionId: "a",
    explanation: { en: "They seek pooled liquidity (stops/orders) retail leaves behind.", tl: "Hinahanap nila ang naka-pool na liquidity na iniwan ng retail." },
  },
  {
    id: "fx23",
    type: "mcq",
    prompt: { en: "AMD stands for…", tl: "Ang AMD ay…" },
    options: [
      { id: "a", text: { en: "Accumulation, Manipulation, Distribution", tl: "Accumulation, Manipulation, Distribution" } },
      { id: "b", text: { en: "Average, Median, Deviation", tl: "Average, Median, Deviation" } },
      { id: "c", text: { en: "Ask, Mid, Demand", tl: "Ask, Mid, Demand" } },
      { id: "d", text: { en: "Advance, Move, Decline", tl: "Advance, Move, Decline" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Accumulation, manipulation (the sweep), distribution (the real move).", tl: "Accumulation, manipulation (ang sweep), distribution (ang totoong galaw)." },
  },

  // ── Fair Value Gap ──
  {
    id: "fx24",
    type: "mcq",
    prompt: { en: "An FVG is a pattern of how many candles?", tl: "Ilang candle ang FVG pattern?" },
    options: [
      { id: "a", text: { en: "Three", tl: "Tatlo" } },
      { id: "b", text: { en: "One", tl: "Isa" } },
      { id: "c", text: { en: "Two", tl: "Dalawa" } },
      { id: "d", text: { en: "Five", tl: "Lima" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Three candles; the gap is on the middle one.", tl: "Tatlong candle; nasa gitnang candle ang gap." },
  },
  {
    id: "fx25",
    type: "mcq",
    prompt: { en: "A bullish FVG is bounded by…", tl: "Ang bullish FVG ay nasa pagitan ng…" },
    options: [
      { id: "a", text: { en: "The high of candle 1 and the low of candle 3", tl: "High ng candle 1 at low ng candle 3" } },
      { id: "b", text: { en: "The low of candle 1 and the high of candle 3", tl: "Low ng candle 1 at high ng candle 3" } },
      { id: "c", text: { en: "Two equal highs", tl: "Dalawang equal highs" } },
      { id: "d", text: { en: "The open and close of candle 2", tl: "Open at close ng candle 2" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Bullish FVG = gap between candle 1's high and candle 3's low.", tl: "Bullish FVG = gap sa pagitan ng high ng candle 1 at low ng candle 3." },
  },
  {
    id: "fx26",
    type: "truefalse",
    prompt: { en: "A single wick through an FVG confirms an inversion.", tl: "Ang isang wick lang sa FVG ay nagkukumpirma ng inversion." },
    options: TF(),
    correctOptionId: "f",
    explanation: { en: "False. A candle BODY close through the FVG signals inversion; a wick is okay.", tl: "Mali. Body close ang nagsa-signal ng inversion; okay ang wick." },
  },
  {
    id: "fx27",
    type: "mcq",
    prompt: { en: "Where do you enter a bullish FVG?", tl: "Saan ka pumapasok sa bullish FVG?" },
    options: [
      { id: "a", text: { en: "At the high of the FVG (or the 50%)", tl: "Sa high ng FVG (o sa 50%)" } },
      { id: "b", text: { en: "At the very bottom", tl: "Sa pinakailalim" } },
      { id: "c", text: { en: "Far above it", tl: "Malayo sa itaas" } },
      { id: "d", text: { en: "Anywhere", tl: "Kahit saan" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Enter at the FVG high or 50%, not the bottom, or a fast move leaves you behind.", tl: "Pumasok sa FVG high o 50%, hindi sa baba, kung hindi maiiwan ka." },
  },
  {
    id: "fx28",
    type: "mcq",
    prompt: { en: "An inversion FVG (IFVG) is…", tl: "Ang inversion FVG (IFVG) ay…" },
    options: [
      { id: "a", text: { en: "An FVG violated by a body close that then flips (support↔resistance)", tl: "FVG na navayolate ng body close tapos bumaliktad (support↔resistance)" } },
      { id: "b", text: { en: "A brand new FVG", tl: "Isang bagong FVG" } },
      { id: "c", text: { en: "A moving average", tl: "Isang moving average" } },
      { id: "d", text: { en: "A swing high", tl: "Isang swing high" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An IFVG flips after a body close through it; old support becomes resistance.", tl: "Bumabaliktad ang IFVG pagkatapos ng body close; ang dating support ay resistance." },
  },

  // ── Order Blocks ──
  {
    id: "fx29",
    type: "mcq",
    prompt: { en: "A bullish order block is the…", tl: "Ang bullish order block ay ang…" },
    options: [
      { id: "a", text: { en: "Last down-close candle before an up-move", tl: "Huling down-close candle bago ang up-move" } },
      { id: "b", text: { en: "Last up-close candle before an up-move", tl: "Huling up-close candle bago ang up-move" } },
      { id: "c", text: { en: "Biggest candle of the day", tl: "Pinakamalaking candle ng araw" } },
      { id: "d", text: { en: "First candle of the week", tl: "Unang candle ng linggo" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Bullish OB = last down-close (red) candle before the rally.", tl: "Bullish OB = huling down-close (pula) na candle bago ang rally." },
  },
  {
    id: "fx30",
    type: "mcq",
    prompt: { en: "When marking an order block you mark the…", tl: "Kapag nag-mark ng order block, mina-mark ang…" },
    options: [
      { id: "a", text: { en: "Candle body only", tl: "Candle body lang" } },
      { id: "b", text: { en: "Full candle with wicks", tl: "Buong candle pati wicks" } },
      { id: "c", text: { en: "Wick only", tl: "Wick lang" } },
      { id: "d", text: { en: "Whole day range", tl: "Buong range ng araw" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Mark the body only; combine consecutive same-color candles.", tl: "Body lang; pagsamahin ang magkakasunod na parehong-kulay." },
  },
  {
    id: "fx31",
    type: "truefalse",
    prompt: { en: "An order block needs an FVG to be high-probability.", tl: "Kailangan ng order block ng FVG para high-probability." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. An OB without an FVG is low-probability.", tl: "Oo. Low-probability ang OB na walang FVG." },
  },
  {
    id: "fx32",
    type: "mcq",
    prompt: { en: "A bearish order block is the…", tl: "Ang bearish order block ay ang…" },
    options: [
      { id: "a", text: { en: "Last up-close candle before a down-move", tl: "Huling up-close candle bago ang down-move" } },
      { id: "b", text: { en: "Last down-close candle before a down-move", tl: "Huling down-close candle bago ang down-move" } },
      { id: "c", text: { en: "Any green candle", tl: "Kahit anong green candle" } },
      { id: "d", text: { en: "The session open", tl: "Ang session open" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Bearish OB = last up-close (green) candle before the drop.", tl: "Bearish OB = huling up-close (green) na candle bago ang bagsak." },
  },
  {
    id: "fx33",
    type: "mcq",
    prompt: { en: "A zone is 'mitigated' when price…", tl: "Ang zone ay 'mitigated' kapag ang price ay…" },
    options: [
      { id: "a", text: { en: "Returns and taps back into it", tl: "Bumalik at tumama pabalik dito" } },
      { id: "b", text: { en: "Ignores it forever", tl: "Binalewala ito habambuhay" } },
      { id: "c", text: { en: "Gaps over it", tl: "Nag-gap dito" } },
      { id: "d", text: { en: "Closes the market", tl: "Isinara ang market" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Mitigation = price returns to tap/wick into the zone.", tl: "Mitigation = pagbalik ng price para tumama sa zone." },
  },

  // ── States of the Market ──
  {
    id: "fx34",
    type: "mcq",
    prompt: { en: "How many states of the market are there?", tl: "Ilan ang states of the market?" },
    options: [
      { id: "a", text: { en: "Four", tl: "Apat" } },
      { id: "b", text: { en: "Two", tl: "Dalawa" } },
      { id: "c", text: { en: "Three", tl: "Tatlo" } },
      { id: "d", text: { en: "Six", tl: "Anim" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Four: consolidation, expansion, retracement, reversal.", tl: "Apat: consolidation, expansion, retracement, reversal." },
  },
  {
    id: "fx35",
    type: "mcq",
    prompt: { en: "Price always moves from a consolidation to…", tl: "Mula consolidation, lagi papuntang…" },
    options: [
      { id: "a", text: { en: "An expansion", tl: "Expansion" } },
      { id: "b", text: { en: "A reversal", tl: "Reversal" } },
      { id: "c", text: { en: "Another consolidation", tl: "Ibang consolidation" } },
      { id: "d", text: { en: "A retracement", tl: "Retracement" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Consolidation always leads to an expansion first.", tl: "Lagi papuntang expansion muna ang consolidation." },
  },
  {
    id: "fx36",
    type: "truefalse",
    prompt: { en: "Price can go straight from a consolidation to a reversal.", tl: "Pwedeng diretso ang price mula consolidation papuntang reversal." },
    options: TF(),
    correctOptionId: "f",
    explanation: { en: "False. A reversal only comes after an expansion; straight from a range it's a trap.", tl: "Mali. Pagkatapos lang ng expansion ang reversal; kung diretso, trap." },
  },
  {
    id: "fx37",
    type: "mcq",
    prompt: { en: "In AMD, the accumulation phase equals which state?", tl: "Sa AMD, ang accumulation ay katumbas ng anong state?" },
    options: [
      { id: "a", text: { en: "Consolidation", tl: "Consolidation" } },
      { id: "b", text: { en: "Expansion", tl: "Expansion" } },
      { id: "c", text: { en: "Reversal", tl: "Reversal" } },
      { id: "d", text: { en: "Retracement", tl: "Retracement" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Accumulation is the consolidation (the range).", tl: "Ang accumulation ay ang consolidation (ang range)." },
  },
  {
    id: "fx38",
    type: "mcq",
    prompt: { en: "A retracement is best described as…", tl: "Ang retracement ay…" },
    options: [
      { id: "a", text: { en: "A pullback within the move", tl: "Pullback sa loob ng move" } },
      { id: "b", text: { en: "A full change of direction", tl: "Buong pagbabago ng direksyon" } },
      { id: "c", text: { en: "A sideways range", tl: "Pa-gilid na range" } },
      { id: "d", text: { en: "A news spike", tl: "Spike dahil sa news" } },
    ],
    correctOptionId: "a",
    explanation: { en: "A retracement is a pullback, not a reversal.", tl: "Ang retracement ay pullback, hindi reversal." },
  },

  // ── OHLC & OLHC ──
  {
    id: "fx39",
    type: "mcq",
    prompt: { en: "OHLC stands for…", tl: "Ang OHLC ay…" },
    options: [
      { id: "a", text: { en: "Open, High, Low, Close", tl: "Open, High, Low, Close" } },
      { id: "b", text: { en: "Order, Hedge, Lot, Cost", tl: "Order, Hedge, Lot, Cost" } },
      { id: "c", text: { en: "Out, Hold, Long, Close", tl: "Out, Hold, Long, Close" } },
      { id: "d", text: { en: "Over, Half, Low, Cap", tl: "Over, Half, Low, Cap" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Open, High, Low, Close, the four prices of a candle.", tl: "Open, High, Low, Close, ang apat na presyo ng candle." },
  },
  {
    id: "fx40",
    type: "mcq",
    prompt: { en: "Reading OHLC/OLHC order inside a candle helps you see…", tl: "Ang pagbasa ng OHLC/OLHC order sa loob ng candle ay tumutulong makita ang…" },
    options: [
      { id: "a", text: { en: "Manipulation before the real move (distribution)", tl: "Manipulation bago ang totoong galaw (distribution)" } },
      { id: "b", text: { en: "The broker's fee", tl: "Ang bayarin ng broker" } },
      { id: "c", text: { en: "The news time", tl: "Ang oras ng news" } },
      { id: "d", text: { en: "Nothing useful", tl: "Walang kapaki-pakinabang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The high/low taken first is the manipulation; the close delivers the real move.", tl: "Ang high/low na nauna ay manipulation; ang close ang totoong galaw." },
  },
  {
    id: "fx41",
    type: "mcq",
    prompt: { en: "In a bullish (OLHC) delivery, after the open price first reaches the…", tl: "Sa bullish (OLHC) delivery, pagkatapos ng open ay nauunang inaabot ang…" },
    options: [
      { id: "a", text: { en: "Low (manipulation down), then delivers up to the close", tl: "Low (manipulation pababa), tapos pataas sa close" } },
      { id: "b", text: { en: "High, then closes lower", tl: "High, tapos close pababa" } },
      { id: "c", text: { en: "Close immediately", tl: "Close agad" } },
      { id: "d", text: { en: "Nothing", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Bullish delivery dips to the low (manipulation) first, then closes up.", tl: "Bumababa muna sa low (manipulation) ang bullish delivery, tapos close pataas." },
  },
  {
    id: "fx42",
    type: "truefalse",
    prompt: { en: "OHLC/OLHC delivery connects to the AMD (manipulation then distribution) idea.", tl: "Ang OHLC/OLHC delivery ay konektado sa AMD (manipulation tapos distribution)." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. The manipulation grabs liquidity before the candle delivers its real move.", tl: "Oo. Kinukuha ng manipulation ang liquidity bago ang totoong galaw ng candle." },
  },

  // ── Liquidity Pools ──
  {
    id: "fx43",
    type: "mcq",
    prompt: { en: "Equal highs or equal lows form a…", tl: "Ang equal highs o equal lows ay bumubuo ng…" },
    options: [
      { id: "a", text: { en: "Liquidity pool (BSL above / SSL below)", tl: "Liquidity pool (BSL itaas / SSL ibaba)" } },
      { id: "b", text: { en: "Moving average", tl: "Moving average" } },
      { id: "c", text: { en: "Trendline channel", tl: "Trendline channel" } },
      { id: "d", text: { en: "Gap", tl: "Gap" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Matching highs/lows pool liquidity just beyond them.", tl: "Ang magkapantay na highs/lows ay nag-iipon ng liquidity lampas dito." },
  },
  {
    id: "fx44",
    type: "mcq",
    prompt: { en: "After sweeping a pool, price often…", tl: "Pagkatapos mag-sweep ng pool, madalas ang price ay…" },
    options: [
      { id: "a", text: { en: "Reverses (MSS) and targets the opposite pool", tl: "Nag-reverse (MSS) at tinatarget ang kabilang pool" } },
      { id: "b", text: { en: "Stops trading", tl: "Tumitigil sa pag-trade" } },
      { id: "c", text: { en: "Stays flat forever", tl: "Patag magpakailanman" } },
      { id: "d", text: { en: "Gaps to zero", tl: "Nag-gap sa zero" } },
    ],
    correctOptionId: "a",
    explanation: { en: "A sweep often flips price (MSS) toward the opposite liquidity.", tl: "Madalas binabaliktad ng sweep ang price (MSS) papunta sa kabilang liquidity." },
  },
  {
    id: "fx45",
    type: "truefalse",
    prompt: { en: "A liquidity sweep is a wick beyond a level that grabs the resting stops.", tl: "Ang liquidity sweep ay wick lampas sa level na kumukuha ng nakahimpil na stops." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. The sweep pokes past the level to take the liquidity, then often reverses.", tl: "Oo. Tumutusok ang sweep lampas sa level para kunin ang liquidity, tapos madalas reversal." },
  },
  {
    id: "fx46",
    type: "mcq",
    prompt: { en: "After sweeping sell-side liquidity, the next draw is often…", tl: "Pagkatapos mag-sweep ng sell-side liquidity, ang susunod na draw ay madalas…" },
    options: [
      { id: "a", text: { en: "The opposite (buy-side) pool", tl: "Ang kabilang (buy-side) pool" } },
      { id: "b", text: { en: "More sell-side below", tl: "Mas maraming sell-side sa ibaba" } },
      { id: "c", text: { en: "The session open only", tl: "Ang session open lang" } },
      { id: "d", text: { en: "Nothing", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Once one side is taken, price draws toward the opposite pool.", tl: "Kapag nakuha ang isang panig, dumadraw ang price papunta sa kabilang pool." },
  },

  // ── Order Flow ──
  {
    id: "fx47",
    type: "mcq",
    prompt: { en: "Order flow tells you…", tl: "Ang order flow ay nagsasabi ng…" },
    options: [
      { id: "a", text: { en: "Where the market is heading (the bias)", tl: "Kung saan papunta ang market (ang bias)" } },
      { id: "b", text: { en: "The exact entry price", tl: "Ang eksaktong entry price" } },
      { id: "c", text: { en: "The broker spread", tl: "Ang broker spread" } },
      { id: "d", text: { en: "The news time", tl: "Ang oras ng news" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Order flow is the directional bias: up if bullish, down if bearish.", tl: "Ang order flow ay ang bias: pataas kung bullish, pababa kung bearish." },
  },
  {
    id: "fx48",
    type: "mcq",
    prompt: { en: "A bullish order flow respects which PDRAs?", tl: "Aling PDRAs ang nire-respeto ng bullish order flow?" },
    options: [
      { id: "a", text: { en: "Bullish PDRAs (and violates bearish ones)", tl: "Bullish PDRAs (at vinavayolate ang bearish)" } },
      { id: "b", text: { en: "Bearish PDRAs only", tl: "Bearish PDRAs lang" } },
      { id: "c", text: { en: "None", tl: "Wala" } },
      { id: "d", text: { en: "Only round numbers", tl: "Round numbers lang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Bullish order flow holds bullish PDRAs and slices through bearish ones.", tl: "Humahawak sa bullish PDRAs ang bullish order flow at dumadaan sa bearish." },
  },
  {
    id: "fx49",
    type: "truefalse",
    prompt: { en: "A lower-timeframe counter-move always means the bias flipped.", tl: "Ang lower-timeframe counter-move ay laging nangangahulugang lumipat ang bias." },
    options: TF(),
    correctOptionId: "f",
    explanation: { en: "False. It may just be the retracement; order flow is fractal, check the HTF.", tl: "Mali. Pwedeng retracement lang; fractal ang order flow, tingnan ang HTF." },
  },
  {
    id: "fx50",
    type: "mcq",
    prompt: { en: "After a retracement to a PDRA, what confirms rejoining the order flow?", tl: "Pagkatapos ng retracement sa PDRA, ano ang nagkukumpirma ng pagbalik sa order flow?" },
    options: [
      { id: "a", text: { en: "An MSS", tl: "Isang MSS" } },
      { id: "b", text: { en: "A round number", tl: "Isang round number" } },
      { id: "c", text: { en: "A red candle", tl: "Isang red candle" } },
      { id: "d", text: { en: "Midnight", tl: "Hatinggabi" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An MSS confirms the retracement is over and the flow resumes.", tl: "Kinukumpirma ng MSS na tapos na ang retracement at tuloy na ang flow." },
  },

  // ── Generated Liquidity ──
  {
    id: "fx51",
    type: "mcq",
    prompt: { en: "Generated liquidity is…", tl: "Ang generated liquidity ay…" },
    options: [
      { id: "a", text: { en: "Liquidity engineered to trap stops, then taken out", tl: "Liquidity na ginawa para ma-trap ang stops, tapos kinuha" } },
      { id: "b", text: { en: "Money lent by a broker", tl: "Pera na pinahiram ng broker" } },
      { id: "c", text: { en: "A moving average", tl: "Isang moving average" } },
      { id: "d", text: { en: "The spread", tl: "Ang spread" } },
    ],
    correctOptionId: "a",
    explanation: { en: "It is liquidity built on purpose to lure stops the algorithm will take.", tl: "Sinadyang ginawa ito para akitin ang stops na kukunin ng algorithm." },
  },
  {
    id: "fx52",
    type: "mcq",
    prompt: { en: "In a low resistance liquidity run (LRLR), the counter-trend swings are…", tl: "Sa low resistance liquidity run (LRLR), ang counter-trend swings ay…" },
    options: [
      { id: "a", text: { en: "Failure swings (don't take the previous swing)", tl: "Failure swings (hindi kinukuha ang nakaraang swing)" } },
      { id: "b", text: { en: "Always reversals", tl: "Palaging reversal" } },
      { id: "c", text: { en: "Gaps", tl: "Mga gap" } },
      { id: "d", text: { en: "Consolidations", tl: "Mga consolidation" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An LRLR glides because its pullbacks are failure swings.", tl: "Gumagliding ang LRLR dahil failure swings ang pullbacks." },
  },
  {
    id: "fx53",
    type: "mcq",
    prompt: { en: "An HRLR (high resistance liquidity run)…", tl: "Ang HRLR (high resistance liquidity run) ay…" },
    options: [
      { id: "a", text: { en: "Takes out the previous high/low each leg (grinds)", tl: "Kinukuha ang nakaraang high/low kada leg (naggiling)" } },
      { id: "b", text: { en: "Never moves price", tl: "Hindi ginagalaw ang price" } },
      { id: "c", text: { en: "Is the same as LRLR", tl: "Pareho ng LRLR" } },
      { id: "d", text: { en: "Only happens on weekends", tl: "Tuwing weekend lang" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An HRLR grinds through liquidity, taking each prior high/low.", tl: "Dumadaan ang HRLR sa liquidity, kinukuha ang bawat high/low." },
  },
  {
    id: "fx54",
    type: "truefalse",
    prompt: { en: "Consolidation and equal highs/lows are forms of generated liquidity.", tl: "Ang consolidation at equal highs/lows ay anyo ng generated liquidity." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes, along with liquidity runs.", tl: "Oo, kasama ng liquidity runs." },
  },

  // ── ERL & IRL ──
  {
    id: "fx55",
    type: "mcq",
    prompt: { en: "Internal range liquidity (IRL) is…", tl: "Ang internal range liquidity (IRL) ay…" },
    options: [
      { id: "a", text: { en: "An FVG inside the range", tl: "FVG sa loob ng range" } },
      { id: "b", text: { en: "The swing high of the range", tl: "Ang swing high ng range" } },
      { id: "c", text: { en: "A moving average", tl: "Isang moving average" } },
      { id: "d", text: { en: "The daily open", tl: "Ang daily open" } },
    ],
    correctOptionId: "a",
    explanation: { en: "IRL is the FVG inside the range.", tl: "Ang IRL ay ang FVG sa loob ng range." },
  },
  {
    id: "fx56",
    type: "mcq",
    prompt: { en: "External range liquidity (ERL) is…", tl: "Ang external range liquidity (ERL) ay…" },
    options: [
      { id: "a", text: { en: "The swing high or low at the range edge", tl: "Ang swing high o low sa gilid ng range" } },
      { id: "b", text: { en: "The FVG in the middle", tl: "Ang FVG sa gitna" } },
      { id: "c", text: { en: "The spread", tl: "Ang spread" } },
      { id: "d", text: { en: "A news event", tl: "Isang news event" } },
    ],
    correctOptionId: "a",
    explanation: { en: "ERL is the swing high/low at the edge of the range.", tl: "Ang ERL ay ang swing high/low sa gilid ng range." },
  },
  {
    id: "fx57",
    type: "mcq",
    prompt: { en: "From an IRL, the next draw is…", tl: "Mula sa IRL, ang susunod na draw ay…" },
    options: [
      { id: "a", text: { en: "The ERL", tl: "Ang ERL" } },
      { id: "b", text: { en: "Another IRL only", tl: "Isa pang IRL lang" } },
      { id: "c", text: { en: "The session open", tl: "Ang session open" } },
      { id: "d", text: { en: "Nothing", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The draw cycles IRL → ERL → IRL.", tl: "Umiikot ang draw IRL → ERL → IRL." },
  },
  {
    id: "fx58",
    type: "truefalse",
    prompt: { en: "The nearest liquidity is the most probable draw, but not guaranteed.", tl: "Ang pinakamalapit na liquidity ang pinaka-malamang na draw, pero hindi garantisado." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Confirm on the lower timeframe before entering.", tl: "Oo. Kumpirmahin sa lower timeframe bago pumasok." },
  },

  // ── Market Structure (Part 2 / advanced) ──
  {
    id: "fx59",
    type: "mcq",
    prompt: { en: "Which highs and lows are protected?", tl: "Aling highs at lows ang protected?" },
    options: [
      { id: "a", text: { en: "Intermediate and long term", tl: "Intermediate at long term" } },
      { id: "b", text: { en: "Short term only", tl: "Short term lang" } },
      { id: "c", text: { en: "None", tl: "Wala" } },
      { id: "d", text: { en: "All of them equally", tl: "Lahat pantay" } },
    ],
    correctOptionId: "a",
    explanation: { en: "ITH/ITL and LTH/LTL are protected; STH/STL are unprotected liquidity.", tl: "Protected ang ITH/ITL at LTH/LTL; unprotected ang STH/STL." },
  },
  {
    id: "fx60",
    type: "mcq",
    prompt: { en: "Stop losses belong…", tl: "Ang stop losses ay dapat…" },
    options: [
      { id: "a", text: { en: "Beyond protected highs/lows, never on STH/STL", tl: "Lampas sa protected highs/lows, hindi sa STH/STL" } },
      { id: "b", text: { en: "On the nearest short-term level", tl: "Sa pinakamalapit na short-term level" } },
      { id: "c", text: { en: "At the entry", tl: "Sa entry" } },
      { id: "d", text: { en: "Anywhere", tl: "Kahit saan" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Hide stops beyond protected levels; short-term levels get taken as liquidity.", tl: "Itago ang stops lampas sa protected levels; kinukuha ang short-term bilang liquidity." },
  },
  {
    id: "fx61",
    type: "mcq",
    prompt: { en: "An intermediate-term high (ITH) has…", tl: "Ang intermediate-term high (ITH) ay may…" },
    options: [
      { id: "a", text: { en: "A short-term high on its left and right", tl: "Short-term high sa kaliwa at kanan" } },
      { id: "b", text: { en: "No highs around it", tl: "Walang highs sa paligid" } },
      { id: "c", text: { en: "Only a moving average", tl: "Isang moving average lang" } },
      { id: "d", text: { en: "A gap on each side", tl: "Gap sa magkabila" } },
    ],
    correctOptionId: "a",
    explanation: { en: "An ITH is flanked by short-term highs on both sides.", tl: "May short-term highs sa magkabila ang ITH." },
  },
  {
    id: "fx62",
    type: "mcq",
    prompt: { en: "Short-term highs/lows behave like which run?", tl: "Ang short-term highs/lows ay parang anong run?" },
    options: [
      { id: "a", text: { en: "LRLR (easily breached)", tl: "LRLR (madaling masira)" } },
      { id: "b", text: { en: "HRLR (hard to breach)", tl: "HRLR (mahirap masira)" } },
      { id: "c", text: { en: "Never breached", tl: "Hindi nasisira" } },
      { id: "d", text: { en: "Not liquidity", tl: "Hindi liquidity" } },
    ],
    correctOptionId: "a",
    explanation: { en: "STH/STL are LRLR: easily taken, then price continues its bias.", tl: "LRLR ang STH/STL: madaling kunin, tapos tuloy ang bias." },
  },

  // ── SMT Divergence ──
  {
    id: "fx63",
    type: "mcq",
    prompt: { en: "SMT divergence is best used as…", tl: "Ang SMT divergence ay pinakamahusay gamitin bilang…" },
    options: [
      { id: "a", text: { en: "A confirmation tool (confluence)", tl: "Confirmation tool (confluence)" } },
      { id: "b", text: { en: "A stand-alone trade idea", tl: "Nag-iisang trade idea" } },
      { id: "c", text: { en: "A leverage setting", tl: "Leverage setting" } },
      { id: "d", text: { en: "A broker choice", tl: "Pagpili ng broker" } },
    ],
    correctOptionId: "a",
    explanation: { en: "SMT is confluence on top of a higher-timeframe bias, not a stand-alone signal.", tl: "Confluence ang SMT dagdag sa HTF bias, hindi nag-iisang signal." },
  },
  {
    id: "fx64",
    type: "mcq",
    prompt: { en: "SMT appears when, between two correlated pairs…", tl: "Lumalabas ang SMT kapag, sa dalawang correlated pair…" },
    options: [
      { id: "a", text: { en: "One stop hunts and the other makes a failure swing", tl: "Isa ang nag-stop hunt at ang isa ay failure swing" } },
      { id: "b", text: { en: "Both stop hunt", tl: "Parehong nag-stop hunt" } },
      { id: "c", text: { en: "Both stay flat", tl: "Parehong patag" } },
      { id: "d", text: { en: "They never correlate", tl: "Hindi sila magka-correlate" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The divergence is one taking its level while the other fails to.", tl: "Ang divergence ay isa kumukuha ng level habang ang isa ay hindi." },
  },
  {
    id: "fx65",
    type: "mcq",
    prompt: { en: "Which asset do you trade on an SMT?", tl: "Aling asset ang ti-trade mo sa SMT?" },
    options: [
      { id: "a", text: { en: "The failure-swing asset", tl: "Ang failure-swing na asset" } },
      { id: "b", text: { en: "The one that stop hunted", tl: "Ang nag-stop hunt" } },
      { id: "c", text: { en: "Whichever has more volume", tl: "Alinmang mas maraming volume" } },
      { id: "d", text: { en: "Neither", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Always trade the failure-swing asset (stronger if bullish, weaker if bearish).", tl: "Palaging i-trade ang failure-swing na asset (malakas kung bullish, mahina kung bearish)." },
  },
  {
    id: "fx66",
    type: "truefalse",
    prompt: { en: "SMT works on its own without any higher-timeframe bias.", tl: "Gumagana ang SMT nang mag-isa na walang higher-timeframe bias." },
    options: TF(),
    correctOptionId: "f",
    explanation: { en: "False. Without a HTF bias, SMT is useless.", tl: "Mali. Kung walang HTF bias, walang silbi ang SMT." },
  },

  // ── Standard Deviation Projection ──
  {
    id: "fx67",
    type: "mcq",
    prompt: { en: "Standard deviation projection measures the…", tl: "Sinusukat ng standard deviation projection ang…" },
    options: [
      { id: "a", text: { en: "Manipulation leg", tl: "Manipulation leg" } },
      { id: "b", text: { en: "Whole week's range", tl: "Buong range ng linggo" } },
      { id: "c", text: { en: "Spread", tl: "Spread" } },
      { id: "d", text: { en: "Volume", tl: "Volume" } },
    ],
    correctOptionId: "a",
    explanation: { en: "You measure the manipulation leg (0 to 1) then project the targets.", tl: "Sinusukat ang manipulation leg (0 hanggang 1) tapos ipo-project ang targets." },
  },
  {
    id: "fx68",
    type: "mcq",
    prompt: { en: "The safest take-profit zone is…", tl: "Ang pinakaligtas na take-profit zone ay…" },
    options: [
      { id: "a", text: { en: "-2 to -2.5", tl: "-2 hanggang -2.5" } },
      { id: "b", text: { en: "0 to 1", tl: "0 hanggang 1" } },
      { id: "c", text: { en: "+5", tl: "+5" } },
      { id: "d", text: { en: "-10", tl: "-10" } },
    ],
    correctOptionId: "a",
    explanation: { en: "-2 to -2.5 is usually enough; -3.5 is the extended target.", tl: "Kadalasan sapat na ang -2 hanggang -2.5; -3.5 ang extended." },
  },
  {
    id: "fx69",
    type: "mcq",
    prompt: { en: "In the session model, accumulation usually happens during…", tl: "Sa session model, ang accumulation ay kadalasang nangyayari sa…" },
    options: [
      { id: "a", text: { en: "The Asian session", tl: "Asian session" } },
      { id: "b", text: { en: "The London session", tl: "London session" } },
      { id: "c", text: { en: "The New York session", tl: "New York session" } },
      { id: "d", text: { en: "The weekend", tl: "Weekend" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Accumulation = Asian, manipulation = London, distribution = New York.", tl: "Accumulation = Asian, manipulation = London, distribution = New York." },
  },
  {
    id: "fx70",
    type: "truefalse",
    prompt: { en: "A projection level needs a confluent higher-timeframe PDRA to matter.", tl: "Ang projection level ay kailangan ng confluent na HTF PDRA para magkasaysay." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. A level alone is not a signal; it needs a HTF PDRA confluence.", tl: "Oo. Hindi signal ang level lang; kailangan ng HTF PDRA confluence." },
  },

  // ── MMXM (Market Maker Models) ──
  {
    id: "fx71",
    type: "mcq",
    prompt: { en: "Which model do you use in a bullish order flow?", tl: "Aling model ang ginagamit sa bullish order flow?" },
    options: [
      { id: "a", text: { en: "The Market Maker Buy Model", tl: "Market Maker Buy Model" } },
      { id: "b", text: { en: "The Market Maker Sell Model", tl: "Market Maker Sell Model" } },
      { id: "c", text: { en: "Neither", tl: "Wala" } },
      { id: "d", text: { en: "Both at once", tl: "Pareho nang sabay" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Buy model in a bullish flow; sell model in a bearish flow.", tl: "Buy model sa bullish flow; sell model sa bearish flow." },
  },
  {
    id: "fx72",
    type: "mcq",
    prompt: { en: "SMR stands for…", tl: "Ang SMR ay…" },
    options: [
      { id: "a", text: { en: "Smart Money Reversal", tl: "Smart Money Reversal" } },
      { id: "b", text: { en: "Standard Market Range", tl: "Standard Market Range" } },
      { id: "c", text: { en: "Stop Money Run", tl: "Stop Money Run" } },
      { id: "d", text: { en: "Slow Market Retrace", tl: "Slow Market Retrace" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The SMR is the reversal at a higher-timeframe PDRA.", tl: "Ang SMR ay ang reversal sa higher-timeframe PDRA." },
  },
  {
    id: "fx73",
    type: "mcq",
    prompt: { en: "An MMBM completes when price reaches…", tl: "Nakukumpleto ang MMBM kapag inabot ng price ang…" },
    options: [
      { id: "a", text: { en: "The original consolidation high", tl: "Ang original consolidation high" } },
      { id: "b", text: { en: "The SMR low again", tl: "Ang SMR low ulit" } },
      { id: "c", text: { en: "A round number", tl: "Isang round number" } },
      { id: "d", text: { en: "The session open", tl: "Ang session open" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The buy model targets and completes at the original consolidation high.", tl: "Tinatarget at nakukumpleto ng buy model ang original consolidation high." },
  },
  {
    id: "fx74",
    type: "truefalse",
    prompt: { en: "Timeframes must be aligned to trade a market maker model.", tl: "Kailangang aligned ang timeframes para i-trade ang market maker model." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes, e.g. monthly → daily → H1, or daily → H1 → M5.", tl: "Oo, hal. monthly → daily → H1, o daily → H1 → M5." },
  },

  // ── Catching Expansions ──
  {
    id: "fx75",
    type: "mcq",
    prompt: { en: "The first step to catch an expansion is to…", tl: "Ang unang hakbang sa paghuli ng expansion ay…" },
    options: [
      { id: "a", text: { en: "Find the draw on liquidity (the target)", tl: "Hanapin ang draw on liquidity (ang target)" } },
      { id: "b", text: { en: "Pick a random entry", tl: "Pumili ng random entry" } },
      { id: "c", text: { en: "Max out leverage", tl: "I-max ang leverage" } },
      { id: "d", text: { en: "Wait for the weekend", tl: "Maghintay ng weekend" } },
    ],
    correctOptionId: "a",
    explanation: { en: "No target, no trade. Find the draw on liquidity first.", tl: "Walang target, walang trade. Hanapin muna ang draw on liquidity." },
  },
  {
    id: "fx76",
    type: "mcq",
    prompt: { en: "A raid on a short-term high promotes it to…", tl: "Ang raid sa short-term high ay nagiging…" },
    options: [
      { id: "a", text: { en: "An intermediate-term high", tl: "Isang intermediate-term high" } },
      { id: "b", text: { en: "A consolidation", tl: "Isang consolidation" } },
      { id: "c", text: { en: "A gap", tl: "Isang gap" } },
      { id: "d", text: { en: "A moving average", tl: "Isang moving average" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The raid promotes the STH to an ITH (market structure).", tl: "Pino-promote ng raid ang STH papuntang ITH." },
  },
  {
    id: "fx77",
    type: "mcq",
    prompt: { en: "You confirm the entry with…", tl: "Kinukumpirma mo ang entry gamit ang…" },
    options: [
      { id: "a", text: { en: "An MSS on the lower timeframe", tl: "MSS sa lower timeframe" } },
      { id: "b", text: { en: "A news alert", tl: "News alert" } },
      { id: "c", text: { en: "A round number", tl: "Round number" } },
      { id: "d", text: { en: "Nothing", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Wait for an MSS on the lower timeframe after the raid.", tl: "Hintayin ang MSS sa lower timeframe pagkatapos ng raid." },
  },
  {
    id: "fx78",
    type: "truefalse",
    prompt: { en: "The second-stage entry is safer because it is closer to the target.", tl: "Mas ligtas ang second-stage entry dahil mas malapit sa target." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Smaller profit, but higher chance of working.", tl: "Oo. Mas maliit na profit, pero mas malaking tsansang gumana." },
  },

  // ── Entry Patterns ──
  {
    id: "fx79",
    type: "mcq",
    prompt: { en: "The bearish entry pattern is read from…", tl: "Ang bearish entry pattern ay binabasa mula sa…" },
    options: [
      { id: "a", text: { en: "The STH-ITH-STH (breaker) trio", tl: "Ang STH-ITH-STH (breaker) trio" } },
      { id: "b", text: { en: "A single candle", tl: "Isang candle" } },
      { id: "c", text: { en: "A moving average cross", tl: "Moving average cross" } },
      { id: "d", text: { en: "The daily open", tl: "Ang daily open" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The entry forms from the short/intermediate-term high trio (the breaker).", tl: "Nabubuo ang entry mula sa STH-ITH-STH trio (ang breaker)." },
  },
  {
    id: "fx80",
    type: "mcq",
    prompt: { en: "The safest stop placement is…", tl: "Ang pinakaligtas na stop placement ay…" },
    options: [
      { id: "a", text: { en: "Beyond the protected ITH/ITL", tl: "Lampas sa protected ITH/ITL" } },
      { id: "b", text: { en: "On the entry zone", tl: "Sa entry zone" } },
      { id: "c", text: { en: "At the target", tl: "Sa target" } },
      { id: "d", text: { en: "Nowhere", tl: "Wala" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The protected ITH/ITL is the safe stop; the short-term level gives more RR but is riskier.", tl: "Ang protected ITH/ITL ang ligtas na stop; mas RR ang short-term pero mas risky." },
  },
  {
    id: "fx81",
    type: "mcq",
    prompt: { en: "Entries tend to cluster at the…", tl: "Ang entries ay madalas nagsisiksikan sa…" },
    options: [
      { id: "a", text: { en: "50% equilibrium of the leg", tl: "50% equilibrium ng leg" } },
      { id: "b", text: { en: "Very top of the leg", tl: "Pinakatuktok ng leg" } },
      { id: "c", text: { en: "Session close", tl: "Session close" } },
      { id: "d", text: { en: "A round number", tl: "Round number" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The 50% is the equilibrium: premium above, discount below.", tl: "Ang 50% ang equilibrium: premium sa itaas, discount sa ibaba." },
  },
  {
    id: "fx82",
    type: "mcq",
    prompt: { en: "Which is NOT one of the entry PDRAs?", tl: "Alin ang HINDI entry PDRA?" },
    options: [
      { id: "a", text: { en: "A moving average crossover", tl: "Moving average crossover" } },
      { id: "b", text: { en: "Breaker block", tl: "Breaker block" } },
      { id: "c", text: { en: "Mitigation block", tl: "Mitigation block" } },
      { id: "d", text: { en: "Inversion FVG", tl: "Inversion FVG" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Entry PDRAs are FVG, breaker, mitigation block, inversion FVG, OB.", tl: "Ang entry PDRAs ay FVG, breaker, mitigation block, inversion FVG, OB." },
  },

  // ── Combining Everything ──
  {
    id: "fx83",
    type: "mcq",
    prompt: { en: "The five-point checklist starts with…", tl: "Ang limang-puntong checklist ay nagsisimula sa…" },
    options: [
      { id: "a", text: { en: "Order flow (your bias)", tl: "Order flow (ang bias mo)" } },
      { id: "b", text: { en: "Position size", tl: "Position size" } },
      { id: "c", text: { en: "The broker spread", tl: "Ang broker spread" } },
      { id: "d", text: { en: "A moving average", tl: "Isang moving average" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Order flow first, then ERL/IRL, liquidity, time, structure.", tl: "Order flow muna, tapos ERL/IRL, liquidity, time, structure." },
  },
  {
    id: "fx84",
    type: "mcq",
    prompt: { en: "EURUSD should be traded during which kill zones?", tl: "Ang EURUSD ay dapat i-trade sa aling kill zones?" },
    options: [
      { id: "a", text: { en: "London and New York", tl: "London at New York" } },
      { id: "b", text: { en: "Asian only", tl: "Asian lang" } },
      { id: "c", text: { en: "Weekends", tl: "Weekends" } },
      { id: "d", text: { en: "Any time", tl: "Kahit kailan" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Trade EURUSD in London/New York; the Asian session is low-probability.", tl: "I-trade ang EURUSD sa London/New York; low-probability ang Asian." },
  },
  {
    id: "fx85",
    type: "truefalse",
    prompt: { en: "With no clear draw on liquidity, even a clean setup is useless.", tl: "Kung walang malinaw na draw on liquidity, walang silbi kahit malinis na setup." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. The target (draw on liquidity) is non-negotiable.", tl: "Oo. Hindi mapag-uusapan ang target (draw on liquidity)." },
  },

  // ── Asian Session Model ──
  {
    id: "fx86",
    type: "mcq",
    prompt: { en: "Asian Session model entries are taken in the…", tl: "Ang entries ng Asian Session model ay sa…" },
    options: [
      { id: "a", text: { en: "London kill zone", tl: "London kill zone" } },
      { id: "b", text: { en: "Asian kill zone", tl: "Asian kill zone" } },
      { id: "c", text: { en: "Weekend", tl: "Weekend" } },
      { id: "d", text: { en: "Any time", tl: "Kahit kailan" } },
    ],
    correctOptionId: "a",
    explanation: { en: "This model focuses on London kill zone entries.", tl: "Nakatuon ang model na ito sa London kill zone entries." },
  },
  {
    id: "fx87",
    type: "mcq",
    prompt: { en: "The best entry timeframe for the Asian model is…", tl: "Ang pinakamagandang entry timeframe sa Asian model ay…" },
    options: [
      { id: "a", text: { en: "M1", tl: "M1" } },
      { id: "b", text: { en: "Daily", tl: "Daily" } },
      { id: "c", text: { en: "Weekly", tl: "Weekly" } },
      { id: "d", text: { en: "Monthly", tl: "Monthly" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Enter on M1 (M5 also works but the range is small).", tl: "Pumasok sa M1 (gumagana rin ang M5 pero maliit ang range)." },
  },
  {
    id: "fx88",
    type: "mcq",
    prompt: { en: "If price raids the Asian high, your target is the…", tl: "Kung rinaid ang Asian high, ang target mo ay ang…" },
    options: [
      { id: "a", text: { en: "Asian low (opposite edge)", tl: "Asian low (kabilang gilid)" } },
      { id: "b", text: { en: "An even higher high", tl: "Mas mataas pang high" } },
      { id: "c", text: { en: "The same high again", tl: "Ang parehong high ulit" } },
      { id: "d", text: { en: "No target", tl: "Walang target" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Target the opposite edge: raid the high, aim for the low.", tl: "I-target ang kabilang gilid: raid ang high, tumudla sa low." },
  },
  {
    id: "fx89",
    type: "truefalse",
    prompt: { en: "If the pattern forms before the kill zone, you should enter immediately.", tl: "Kung nabuo ang pattern bago ang kill zone, dapat pumasok agad." },
    options: TF(),
    correctOptionId: "f",
    explanation: { en: "False. Wait for the kill zone; price often keeps running out of the zone otherwise.", tl: "Mali. Hintayin ang kill zone; kung hindi, madalas tuloy ang price palabas ng zone." },
  },

  // ── Main Model ──
  {
    id: "fx90",
    type: "mcq",
    prompt: { en: "In the main model, the higher timeframe gives you the…", tl: "Sa main model, ang higher timeframe ay nagbibigay ng…" },
    options: [
      { id: "a", text: { en: "Draw on liquidity (your bias)", tl: "Draw on liquidity (ang bias mo)" } },
      { id: "b", text: { en: "Exact entry candle", tl: "Eksaktong entry candle" } },
      { id: "c", text: { en: "Stop loss size only", tl: "Laki ng stop loss lang" } },
      { id: "d", text: { en: "The spread", tl: "Ang spread" } },
    ],
    correctOptionId: "a",
    explanation: { en: "HTF = draw on liquidity/bias; intermediate = raid; lower = entry.", tl: "HTF = draw on liquidity/bias; intermediate = raid; lower = entry." },
  },
  {
    id: "fx91",
    type: "mcq",
    prompt: { en: "The core trigger of the main model is the…", tl: "Ang pangunahing trigger ng main model ay ang…" },
    options: [
      { id: "a", text: { en: "Raid (stop hunt) that takes liquidity", tl: "Raid (stop hunt) na kumukuha ng liquidity" } },
      { id: "b", text: { en: "Filling a specific FVG", tl: "Pagpuno ng partikular na FVG" } },
      { id: "c", text: { en: "A news headline", tl: "News headline" } },
      { id: "d", text: { en: "A round number", tl: "Round number" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The raid is the trigger; filling an FVG is helpful but not required.", tl: "Ang raid ang trigger; nakakatulong ang FVG pero hindi kailangan." },
  },
  {
    id: "fx92",
    type: "mcq",
    prompt: { en: "The minimum target for the main model is…", tl: "Ang minimum na target ng main model ay…" },
    options: [
      { id: "a", text: { en: "1:2", tl: "1:2" } },
      { id: "b", text: { en: "1:0.5", tl: "1:0.5" } },
      { id: "c", text: { en: "100:1", tl: "100:1" } },
      { id: "d", text: { en: "No target", tl: "Walang target" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Minimum 1:2, and 1:3 for very high-probability draws.", tl: "Minimum 1:2, at 1:3 para sa napakataas na probability." },
  },
  {
    id: "fx93",
    type: "truefalse",
    prompt: { en: "You should only trade with the higher-timeframe bias, never retracements.", tl: "Dapat mag-trade lang kasama ang higher-timeframe bias, hindi retracements." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Counter-trend retracement entries are low probability.", tl: "Oo. Low probability ang counter-trend retracement entries." },
  },

  // ── Previous Day High & Low Model ──
  {
    id: "fx94",
    type: "mcq",
    prompt: { en: "The Previous Day model's entry timeframe is…", tl: "Ang entry timeframe ng Previous Day model ay…" },
    options: [
      { id: "a", text: { en: "M5", tl: "M5" } },
      { id: "b", text: { en: "Monthly", tl: "Monthly" } },
      { id: "c", text: { en: "Weekly", tl: "Weekly" } },
      { id: "d", text: { en: "H4", tl: "H4" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Entries on M5; higher timeframes are the 1H and daily.", tl: "Entries sa M5; higher timeframes ay 1H at daily." },
  },
  {
    id: "fx95",
    type: "mcq",
    prompt: { en: "If price takes the previous day low and shows NO MSS, you…", tl: "Kung kinuha ng price ang previous day low at WALANG MSS, ikaw ay…" },
    options: [
      { id: "a", text: { en: "Do not enter (it is a continuation)", tl: "Huwag pumasok (continuation iyon)" } },
      { id: "b", text: { en: "Buy immediately", tl: "Bumili agad" } },
      { id: "c", text: { en: "Double your size", tl: "Doblehin ang size" } },
      { id: "d", text: { en: "Short the breakout", tl: "I-short ang breakout" } },
    ],
    correctOptionId: "a",
    explanation: { en: "No MSS = continuation; the model does not apply, so stand aside.", tl: "Walang MSS = continuation; hindi applicable, kaya tumabi." },
  },
  {
    id: "fx96",
    type: "mcq",
    prompt: { en: "A reversal from the previous day low targets the…", tl: "Ang reversal mula sa previous day low ay tinatarget ang…" },
    options: [
      { id: "a", text: { en: "Previous day high", tl: "Previous day high" } },
      { id: "b", text: { en: "An even lower low", tl: "Mas mababa pang low" } },
      { id: "c", text: { en: "The same low", tl: "Ang parehong low" } },
      { id: "d", text: { en: "No target", tl: "Walang target" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Target the opposite extreme, the previous day high (or a fixed 1:2/1:3).", tl: "I-target ang kabilang extreme, ang previous day high (o fixed 1:2/1:3)." },
  },

  // ── Synthesis ──
  {
    id: "fx97",
    type: "truefalse",
    prompt: { en: "Trading is a game of probability; no strategy wins 100% of the time.", tl: "Laro ng probability ang trading; walang strategy na nananalo 100%." },
    options: TF(),
    correctOptionId: "t",
    explanation: { en: "Yes. Follow the rules and target correctly; losses are normal.", tl: "Oo. Sundin ang rules at mag-target nang tama; normal ang talo." },
  },
  {
    id: "fx98",
    type: "mcq",
    prompt: { en: "'Less is more' means…", tl: "Ang 'less is more' ay nangangahulugang…" },
    options: [
      { id: "a", text: { en: "Fewer, cleaner trades beat chasing every move", tl: "Mas kaunti at malinis na trades kaysa habulin lahat" } },
      { id: "b", text: { en: "Use the smallest timeframe always", tl: "Gamitin ang pinakamaliit na timeframe lagi" } },
      { id: "c", text: { en: "Risk less than 1 pip", tl: "Mag-risk ng wala pang 1 pip" } },
      { id: "d", text: { en: "Trade only one pair forever", tl: "Mag-trade ng isang pair lang habambuhay" } },
    ],
    correctOptionId: "a",
    explanation: { en: "Quality over quantity protects your account and your psychology.", tl: "Kalidad kaysa dami, pinoprotektahan ang account at psychology." },
  },
  {
    id: "fx99",
    type: "mcq",
    prompt: { en: "Across the course, the entry confirmation is almost always an…", tl: "Sa buong course, ang entry confirmation ay halos lagi ay…" },
    options: [
      { id: "a", text: { en: "MSS (Market Structure Shift)", tl: "MSS (Market Structure Shift)" } },
      { id: "b", text: { en: "RSI crossover", tl: "RSI crossover" } },
      { id: "c", text: { en: "News release", tl: "News release" } },
      { id: "d", text: { en: "Round number", tl: "Round number" } },
    ],
    correctOptionId: "a",
    explanation: { en: "The MSS confirms the turn before you enter, again and again.", tl: "Kinukumpirma ng MSS ang liko bago pumasok, paulit-ulit." },
  },
  {
    id: "fx100",
    type: "mcq",
    prompt: { en: "A PDRA is best described as…", tl: "Ang PDRA ay pinakamahusay ilarawan bilang…" },
    options: [
      { id: "a", text: { en: "A zone Smart Money reacts from (OB, FVG, breaker)", tl: "Zone kung saan tumutugon ang Smart Money (OB, FVG, breaker)" } },
      { id: "b", text: { en: "A type of moving average", tl: "Isang uri ng moving average" } },
      { id: "c", text: { en: "A broker order", tl: "Isang broker order" } },
      { id: "d", text: { en: "A news calendar", tl: "Isang news calendar" } },
    ],
    correctOptionId: "a",
    explanation: { en: "PDRAs are the price zones Smart Money reacts from: OBs, FVGs, breakers, and more.", tl: "Ang PDRAs ay ang mga zone kung saan tumutugon ang Smart Money: OBs, FVGs, breakers." },
  },
];
